### ISSUE TITLE
a websocket interface more like phoenix channels

### ISSUE THREAD

**Issue by jbr** [trillium-rs/trillium#11]
probably built on top of the current websocket handler

**Comment by redmar** [comment]
do you have the intention to stay/be compatible with phoenix channels so you could re-use phoenix.js on the frontend while having a phoenix channels compatible back-end? Seems the channels abstraction is quite nice and thin/easy to implement.

**Comment by jbr** [comment]
I haven't thought about it with much detail, but starting out compatible seems like a good initial target (and decreases the js I need to maintain)

Eventually I'd prefer the client side to be written in fully typed typescript or rust/wasm

**Comment by jbr** [comment]
Especially if I ever take on something like liveview, I'd certainly want it to be a wasm client. But that's way down the line, and probably would require sponsors

**Comment by jbr** [comment]
[trillium-channels v0.1.0](https://docs.rs/trillium-channels/0.1.0/trillium_channels/) has now been released, offering a phoenix-channels compatible backend for trillium
