### ISSUE TITLE
trillium-static should respect If-None-Match and ETag and return no content if it matches

### ISSUE THREAD

**Issue by prabirshrestha** [trillium-rs/trillium#147]
Seems like trillium-static sends the file with correct response headers but never looks at the request header and always sends the full response body instead of a `304 Not Modified`. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#caching_of_unchanged_resources
> The server compares the client's ETag (sent with If-None-Match) with the ETag for its current version of the resource, and if both values match (that is, the resource has not changed), the server sends back a 304 Not Modified status, without a body, which tells the client that the cached version of the response is still good to use (fresh).

**Comment by jbr** [comment]
You must use the trillium-caching-headers crate to enable this functionality

**Comment by prabirshrestha** [comment]
I tried adding and it doesn't seem to work. Most likely could be something wrong on my side?

https://github.com/prabirshrestha/rblog/pull/22

If I go to http://localhost:8080/posts/welcome/attachment.txt It always return 200ok though the etag/modifed headers are sent correctly both in request and response.

**Comment by jbr** [comment]
with that pr i'm seeing:

initial load:
```
::1 bebpudo52Q - [09/Dec/2021:20:19:19 -0800] "GET /posts/welcome/attachment.txt HTTP/1.1" 200 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
```
then on reload
```
::1 fK70HW3NYJ - [09/Dec/2021:20:19:23 -0800] "GET /posts/welcome/attachment.txt HTTP/1.1" 304 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
```

**Comment by prabirshrestha** [comment]
Seems to work correctly. Sorry for the false alarm. More of an issue with chrome UI.
