### ISSUE TITLE
Feature suggestion for `trillium-websockets`: Make websocket limits configurable

### ISSUE THREAD

**Issue by dexgs** [trillium-rs/trillium#174]
By default, tungstenite imposes a message size limit of about [67 megabytes](https://docs.rs/tungstenite/latest/src/tungstenite/protocol/mod.rs.html#65). Unless I am missing something, these limits don't seem to be configurable in trillium. This isn't the end of the world, but I would like to be able to set more conservative limits as the defaults far exceed the largest messages permitted by my application.

**Comment by jbr** [comment]
released as [trillium-websockets@0.5.0](https://github.com/trillium-rs/trillium/releases/trillium-websockets-v0.5.0) (minor release because it also upgrades tungstenite)

**Comment by jbr** [comment]
(specifically, [`WebSocket::with_protocol_config`](https://docs.rs/trillium-websockets/latest/trillium_websockets/struct.WebSocket.html#method.with_protocol_config)

**Comment by dexgs** [comment]
This is perfect. Thank you for the quick response.
