### ISSUE TITLE
Feature suggestion for `trillium-router`: Allow `String` or `&str` to be used as the path

### ISSUE THREAD

**Issue by jalcine** [trillium-rs/trillium#194]
<p>While working on <a href="https://indieweb.org/Lighthouse">Lighthouse</a>, I wanted a way to 'build' route URLs for use elsewhere (like returning in a page or in my case, checking if it's referenced in a remote document as part of <a href="https://www.w3.org/TR/webmention/#sender-discovers-receiver-webmention-endpoint">Webmention discovery</a>). I attempted to do the following to build my paths—a change from manually writing in the URL, and it didn't work. It looks like <a href="https://docs.rs/routefinder/latest/routefinder/struct.RouteSpec.html#impl-TryFrom%3CString%3E"><code>TryFrom<string> for RouteSpec</string></code></a> <em>is</em> a thing, so I'm curious as to why it's been restricted to require a lifetime across the entire application.</p>
<div>
<pre>    static URL_PATH_WEBMENTION_PREFIX: &amp;str = "/endpoints/webmention";

    Router::build(|mut router| {
        let path = format!("{}/:token", URL_PATH_WEBMENTION_PREFIX).as_str();

        // This _will_ fail, I did `path.as_str()` initially but of course, that's a short-lived reference.
        router.get(path, |conn: Conn| async move { conn.halt() })
    })
</pre>
</div>

(Originally posted at https://jacky.wtf/2022/4/nS/nSsFq7XHDUUOpXCc6ptwtfOx)

**Comment by jbr** [comment]
Will release this later today as a patch (since it's backwards-compatible)

**Comment by jalcine** [comment]
Amazing! Thank you!

(Originally published at: https://jacky.wtf/2022/4/JI/JIDmPVkep2BrtKWvSpIaE-Px)

**Comment by jbr** [comment]
Released as [trillium-router@v0.3.3](https://github.com/trillium-rs/trillium/releases/tag/trillium-router-v0.3.3)
