### ISSUE TITLE
feature for all runtime adapters: add the ability to provide a pre-bound TcpListener instead of host+port

### ISSUE THREAD

**Issue by jbr** [trillium-rs/trillium#200]
from #198

**Comment by joshtriplett** [comment]
I'd like this as well, so that I can bind to a privileged port and then drop privileges.

**Comment by jbr** [comment]
This is released as [`Config::with_prebound_server`](https://docs.rs/trillium-server-common/latest/trillium_server_common/struct.Config.html#method.with_prebound_server) as patch releases for all three runtimes (trillium-tokio-v0.3.2, trillium-async-std-v0.3.1, and trillium-smol-v0.3.1). Example usage for tokio is at [tokio/examples/tokio_binding.rs](exhttps://github.com/trillium-rs/trillium/blob/main/tokio/examples/tokio_binding.rs) and usage is identical for the other two runtimes.

**Comment by joshtriplett** [comment]
@jbr That's incredible, thank you!
