### ISSUE TITLE
Bug report for `trillium-testing & trillium-static`: Documentation is failing to build on docs.rs

### ISSUE THREAD

**Issue by mathiversen** [trillium-rs/trillium#202]
**Describe the bug**
[Testing](https://docs.rs/crate/trillium-testing/latest)
[Static](https://docs.rs/crate/trillium-static/latest)

**To Reproduce**
See above

**Expected behavior**
Working docs.

**Additional context**
I didn't know that you can send features as metadata to cargo, and i think that's the solution here as I assume you don't want to have a default feature. I can try and create a little pr for this.

**Comment by jbr** [comment]
Closed by #203, thank you!
