### ISSUE TITLE
Feature suggestion for `trillium-websocket`: Add access to peer_ip from WebSocketConn

### ISSUE THREAD

**Issue by enderger** [trillium-rs/trillium#221]
Currently, there is no way to access some methods of `trillium::Conn` from `trillium_websocket::WebSocketConn`, with the same issues as to require `trillium::Conn`'s own `.inner` escape hatch. Alternatively, exposing said hatch of `trillium::Conn` would also be viable to provide such access to lower-level methods.

**Comment by jbr** [comment]
Which methods? WebsocketConn does not contain a Conn, but we can move data over to the WebSocketConn. What specific data do you want?

**Comment by jbr** [comment]
released as [`trillium-websockets@v0.5.1`](https://github.com/trillium-rs/trillium/releases/tag/trillium-websockets-v0.5.1)

**Comment by enderger** [comment]
Thanks, having it definitely allows us to simplify things that need access to it.
