### ISSUE TITLE
Feature suggestion for `trillium-api`: ApiConnExt should include is_json_request() 

### ISSUE THREAD

**Issue by prabirshrestha** [trillium-rs/trillium#226]
This is primarily used for content negotiation or special handling for api vs non api requests.

```rust
pub async fn not_found(conn: Conn) -> Conn {
    if conn.is_json_request() {
      conn.with_status(404).with_json(JsonError { message = "Not found", code = "NotFound" }).halt()
    } else {
       conn.with_status(404).with_body("Not Found").halt()
    }
    
}
```

**Comment by jbr** [comment]
Closing this issue as it was written in regards to trillium-api-v0.1. Additionally, "json request" is unclear, as it could either refer to Accept or Content-Type. In the example above, it is being used to determine response format, which should be based on the Accept header, but #227 uses Content-Type.
