### ISSUE TITLE
add set_json in trillium::ApiConnExt

### ISSUE THREAD

**Issue by prabirshrestha** [trillium-rs/trillium#228]
When using [trillium-error](https://github.com/prabirshrestha/trillium-error) it takes `&mut Conn`.

Would need to add support for the following.

```
fn set_json(&mut self, response: &impl Serialize) -> Result<(), JsonValue>;
```

**Comment by jbr** [comment]
This is resolved by trillium-api-v0.2.0, currently in a RC.2 release. Closing this issue
