### ISSUE TITLE
Feature suggestion for `trillium-server-common`: init with TcpListener rather than host and port

### ISSUE THREAD

**Issue by djarb** [trillium-rs/trillium#231]
In addition to Config::with_host and Config::with_port, it would be great to have a

Config::with_listener(listener: TcpListener) -> Config { todo! }

This would allow initialization to a randomly chosen port number, among other things.

Currently, you can pass 0 to Config::with_port and it will choose a random available port when the internal TcpListener is initialized, but there is no good way to find out what port was selected.

**Comment by jbr** [comment]
Hi, and thanks for using Trillium!

There are two things here. The first is a dupe of #200, and this is a good reminder for me of that issue.

The second is that you can find out the selected port using the [`Info`](https://docs.trillium.rs/trillium/struct.info) passed into an [`Init`](https://docs.trillium.rs/trillium/struct.init) handler

**Comment by djarb** [comment]
I really appreciate your work, and the Init handler is a great tool which I hadn't noticed, so thanks for pointing it out. It doesn't solve my use case, though, since I need to know what port was selected _before_ the server task is launched. Regardless, since this is a dupe, I'll close in favor of #200, and thanks again,
