### ISSUE TITLE
add support for ructe templates

### ISSUE THREAD

**Issue by prabirshrestha** [trillium-rs/trillium#24]
Add [ructe](https://github.com/kaj/ructe) templating support. It catches most of the errors at compile time and also has an optional SASS compilation support to convert it to CSS. 

//cc @kaj

**Comment by jbr** [comment]
This seems like it would be a great addition, but given how many other framework-essential handlers I need to write (#17) and given that there are three template languages currently, I'd be more inclined to advise and review if someone else wants to write it, and would happily add it to the documentation.
