### ISSUE TITLE
Feature suggestion for `trillium`: Lifetimes of Headers::get should be more flexible

### ISSUE THREAD

**Issue by divergentdave** [trillium-rs/trillium#310]
In a function that takes `&Conn`, I tried passing a `String` to `conn.request_headers().get(...)`, and I got a lifetime error. This method's signature is `pub fn get<'a>(&'a self, name: impl Into<HeaderName<'a>>) -> Option<&'a HeaderValue>`. The string implements `Into<HeaderName<'static>>`, but of course the lifetime of the connection reference is not `'static`. I was able to fix my error by writing `conn.request_headers().get(string.as_str())` instead. I think the method signature should be changed to `pub fn get<'a, 'b>(&'a self, name: impl Into<HeaderName<'b>>) -> Option<&'a HeaderValue>` if possible, since the name is not part of the returned value.

**Comment by jbr** [comment]
closed in #312, released as [`trillium-http@v0.2.14`](https://github.com/trillium-rs/trillium/releases/tag/trillium-http-v0.2.14)
