### ISSUE TITLE
Bug report for `trillium-api`: Unclear how to avoid default error handler

### ISSUE THREAD

**Issue by joshtriplett** [trillium-rs/trillium#389]
**Describe the bug**
`trillium_api::ApiHandler` only calls `run` on the returned `Handler`; it never calls `before_send`. This prevents the returned `Handler` type from being able to do its own error handling or other `before_send` functionality.

I think, since `ApiHandler` is *wrapping* a handler, it should call `run` on that handler and then immediately call `before_send` on the same handler.

**To Reproduce**
Run a server using `trillium_api::api` wrapped around a function returning a `Handler` that provides a `before_send` function. Note that the function never gets called.

**Comment by jbr** [comment]
While this makes sense, I'm not sure if this is a bug or a failure of documentation. Could you describe how you're using trillium_api?

**Comment by joshtriplett** [comment]
@jbr I'm using `api` as normal, but I'd like to override the default error handler so that I can send something other than JSON errors, for compatibility with an existing interface.

**Comment by jbr** [comment]
Ahh! I do think that's either a matter of documentation or a poor design decision about the default error handler, which is why it's probably best to start with intent instead of code requests. Adding the before_send handler (which is addressed on main) does not in fact solve this concern, as the before_send is not run if the handler is not run, for example if the body fails to deserialize.

My intent was as follows, and this either needs to be substantially better documented:

```rust

async fn post(_conn: &mut Conn, Body(_): Body<Vec<String>>) -> impl Handler {
    trillium::Status::Ok
}

struct HandleErrors;

#[trillium::async_trait]
impl Handler for HandleErrors {
    async fn run(&self, conn: Conn) -> Conn {
        conn
    }
    async fn before_send(&self, mut conn: Conn) -> Conn {
        if let Some(error) = conn.take_state::<Error>() {
            conn.with_json(&json!({ "custom": "error", "here": error }))
        } else {
            conn
        }
    }
}

fn main() {
    trillium_smol::run((api(post), HandleErrors));
}
```

**Comment by jbr** [comment]
In general, a pattern that I expect will be common enough that it's worth documenting is for an application to have an error-catching handler that runs at the end of the stack and that checks for the presence of any number of errors in state and formats the response appropriately.

As a real-world example of exactly this pattern, see https://github.com/divviup/divviup-api/blob/main/src/handler/error.rs

**Comment by joshtriplett** [comment]
@jbr Ah, I see; thank you for clarifying that!

And if I'm understanding how `before_send` gets sequenced, it should suffice to have a *single* `before_send`-based error `Handler` after the entire router, rather than repeating one at the end of every endpoint.

It wasn't obvious to me, when first using Trillium, when I'd ever want to *not* halt at the end of a handler, and I'm now starting to get an idea of why not to.

Right now, my approach to error handling looks like this:

```rust
#[trillium::async_trait]
impl Handler for ApiError {
    async fn run(&self, mut conn: Conn) -> Conn {
        match self {
            ApiError::Visible(status, err) => {
                tracing::Span::current().record("error", &tracing::field::debug(err));
                conn.set_status(*status);
                conn.set_body(err.to_string())
            }
            ApiError::Invisible(err) => {
                tracing::Span::current().record("error", &tracing::field::debug(err));
                conn.set_status(Status::InternalServerError);
                conn.set_body(Status::InternalServerError.canonical_reason())
            }
        }
        conn.halt()
    }
}

type ApiResult<T> = Result<T, ApiError>;

/// Convert any `Result` to an `ApiResult` to define user visibility
trait ApiResultExt {
    type R;
    fn invis(self) -> Self::R;
    fn visible(self) -> Self::R;
    fn visible_s(self, status: impl TryInto<Status>) -> Self::R;
}
```

Then, I can write `api(handle_foo_post)` where:

```rust
async fn handle_foo_post(
    conn: &mut Conn,
    (State(x), Body(y)): (State<TypeX>, Body<TypeY>),
) -> ApiResult<Body<SomeStruct>> {
    ...
}
```

And then use `?` freely within `handle_foo_post` as long as I use either `.invis()` (for errors that should be hidden behind "Internal Server Error") or `.visible()` (for errors whose text is suitable for human consumption) first.

This works great, except that it doesn't let me avoid the default error handler. Sounds like I should be putting the `ApiError` into the `Conn` as state, and then putting in my own error handler at the end that handles both that and `trillium_api`'s Error type.

**Comment by joshtriplett** [comment]
Closing this as it now seems fairly clear how to avoid the default error handling.
