### ISSUE TITLE
Support for Server Sent Events

### ISSUE THREAD

**Issue by ekanna** [trillium-rs/trillium#39]
Please provide support for Server Sent Events (SSE)

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

**Comment by jbr** [comment]
What is your use case for server sent events that isn't met by websockets? I'm not opposed to building sse support but I want to understand the use case

**Comment by jbr** [comment]
Regardless, one of the benefits of trillium's architecture is that anyone can implement sse support as an ecosystem library. I'm going to convert this issue into a discussion, since it's a proposal for a new crate that someone could write
