### ISSUE TITLE
Bug report for `trillium-api`: Please publish current version with afabe441cbee3322ebfd03357a25862c6b6ef7eb included

### ISSUE THREAD

**Issue by joshtriplett** [trillium-rs/trillium#425]
I'm currently using the new `trillium-api` with afabe441cbee3322ebfd03357a25862c6b6ef7eb included, successfully, and serving up a websocket.

Could you please publish an updated `trillium-api` crates.io with that commit included, so that I can use it without a git dependency?

Thank you!

**Comment by jbr** [comment]
Released as [0.2.0-rc.5](https://crates.io/crates/trillium-api/0.2.0-rc.5) — I think with the changes in #428 and some further documentation and examples, this approach will be good to go as `0.2.0`.
