### ISSUE TITLE
Bug report for `trillium-rustls`: Please publish a new version with 6a72b1b0ea51e638ee92b0e45a3a8f3bcde69f62 included

### ISSUE THREAD

**Issue by joshtriplett** [trillium-rs/trillium#429]
Would it be possible to get a `trillium-rustls` 0.4.1 package with commit 6a72b1b0ea51e638ee92b0e45a3a8f3bcde69f62 included?

Thank you!

**Comment by jbr** [comment]
I believe this is resolved by the recent batch of releases
