### ISSUE TITLE
Running code after response is sent

### ISSUE THREAD

**Issue by hasali19** [trillium-rs/trillium#49]
Trillium looks really nice and I thought I'd give it a go for a small project. I was wondering if it's possible to run some code after the response is finished? I have a situation where I need to perform an operation that will affect the machine's ability to send a response, so this can only be started once the response has actually been sent.

**Comment by jbr** [comment]
What's the specific use case? There isn't currently a way to do that*, but potentially we could add an after_send hook. It would add a significant amount of complexity, so I'd want to really be sure that it was necessary.

What information would you want to have access to in the after_send hook? Would it need to be async? If it's async and there's a subsequent request on the same keepalive connection while we're awaiting the after send block, do we start processing the next request? Would you want the after_send hook to run if the client disconnects before we finish sending the response body?

*If you don't need to know whether the response was fully written, it would work today to add a type that has a Drop implementation to the Conn state set. If it needs to do async work there, spawn a task from Drop.

**Comment by jbr** [comment]
> need to perform an operation that will affect the machine's ability to send a response

This sounds like maybe you want to shut down the server when the request is finished? There's a way to do that currently

**Comment by hasali19** [comment]
My use case is that I need to run some stuff and then put the machine to sleep. Thinking about it though, shutting down the server would be a good solution, assuming I can run code after the server has shut down. How would I go about doing that when the request is finished?

**Comment by hasali19** [comment]
Never mind, found `Stopper` in the docs. This works perfectly, thanks!
