### ISSUE TITLE
Request to publish trillium-static to crates.io

### ISSUE THREAD

**Issue by soukyo** [trillium-rs/trillium#55]

**Comment by jbr** [comment]
Will do so today. Out of curiosity, which runtime are you using? The reason I haven't published it yet is that there isn't currently a tokio-flavored version

**Comment by jbr** [comment]
released [trillium-static v0.1.0](https://crates.io/crates/trillium-static) — please note that unlike the other trillium crates, this currently [temporarily] requires setting a cargo feature flag of either `smol`, `async-std`, or `tokio`, and will not compile unless one of these is set
