### ISSUE TITLE
Bug report for `trillium-proxy`: Compilation fails with --no-default-features

### ISSUE THREAD

**Issue by divergentdave** [trillium-rs/trillium#587]
**Describe the bug**
`trillium-proxy` cannot be built without the `upstream-connection-counting` feature enabled.

**To Reproduce**
`cargo check -p trillium-proxy --no-default-features`

```
error[E0432]: unresolved import `trillium_server_common`
 --> proxy/src/forward_proxy_connect.rs:6:5
  |
6 | use trillium_server_common::{Connector, ObjectSafeConnector};
  |     ^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `trillium_server_common`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `trillium-proxy` (lib) due to 1 previous error
```

**Expected behavior**
Successful compilation

**Comment by jbr** [comment]
Thanks for reporting! Fix released as [trillium-proxy@0.5.3](https://github.com/trillium-rs/trillium/releases/tag/trillium-proxy-v0.5.3)
