### ISSUE TITLE
querystring support

### ISSUE THREAD

**Issue by jbr** [trillium-rs/trillium#6]
with [querystrong](https://github.com/jbr/querystrong)

**Comment by hasali19** [comment]
Any progress on this? It would at least be helpful to expose the raw path/query string to parse manually but I don't think this is currently done. I saw the [`path`](https://docs.trillium.rs/trillium/struct.conn#method.path) method which looks like it should return the request path but it only seems to return the last segment.

**Comment by jbr** [comment]
I have not done this yet. I will update this issue when I do

**Comment by mathiversen** [comment]
I think it would be good to also expose a querystring method on the WebsocketConn. While working with websockets i noticed that you can't change the request headers in the current browser implementations of websockets so to pass a token you sort of have to use queries.

**Comment by jbr** [comment]
@mathiversen I've added WebsocketConn::querystring in [trillium-websockets@v0.2.0](https://github.com/trillium-rs/trillium/releases/tag/trillium-websockets-v0.2.0)
