### ISSUE TITLE
Feature suggestion for `trillium-api` 0.2.0-rc.11: Replace `<Vec<u8> as FromConn>` with `<Vec<u8> as TryFromConn>`

### ISSUE THREAD

**Issue by divergentdave** [trillium-rs/trillium#647]
I've been using `trillium-api` together with `trillium-opentelemetry`, and with `ApiHandler` methods that take the request body as a `Vec<u8>`. When a client connection is interrupted before its entire request can be received, this causes spurious metrics observations of `http.server.request.duration` with `http.response.status_code` set to "404". This is happening because the `FromConn` implementation for `Vec<u8>` encounters an error when reading the request body, and returns `None`. As a result, the `ApiHandler` doesn't get run, and a fallback error handler of `()` is run on the connection instead. This `FromConn` implementation (and the one for `String`) could be replaced with a `TryFromConn` implementation that returns `Status::BadRequest` as an error handler. This would provide more reasonable metrics values in this situation. See https://github.com/divviup/janus/issues/2515#issuecomment-2136198887.

**Comment by jbr** [comment]
This seems entirely reasonable. I'll get a release out later today or tomorrow!
